/*
 * JS for A0HomePageOrg generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ac2f1913-e4fd-4043-aae9-c940ec4861d1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "L1SubmitAdvertisingPage",
    "location": "L1SubmitAdvertisingPage.html"
}, {
    "name": "XAdDialog07",
    "location": "XAdDialog07.html"
}, {
    "name": "XAdDialog05",
    "location": "XAdDialog05.html"
}, {
    "name": "XAdDialog08",
    "location": "XAdDialog08.html"
}, {
    "name": "XAdDialog03",
    "location": "XAdDialog03.html"
}, {
    "name": "XAdDialog02",
    "location": "XAdDialog02.html"
}, {
    "name": "L3TermsandConditionsPage",
    "location": "L3TermsandConditionsPage.html"
}, {
    "name": "XAdDialog04",
    "location": "XAdDialog04.html"
}, {
    "name": "YBridesSonar20170101002",
    "location": "YBridesSonar20170101002.html"
}, {
    "name": "YBridesSonar20170101003",
    "location": "YBridesSonar20170101003.html"
}, {
    "name": "D2EditProfilePage",
    "location": "D2EditProfilePage.html"
}, {
    "name": "L4DeveloperPage",
    "location": "L4DeveloperPage.html"
}, {
    "name": "J1SubmitTestimonialsPage",
    "location": "J1SubmitTestimonialsPage.html"
}, {
    "name": "B0AboutUsPage",
    "location": "B0AboutUsPage.html"
}, {
    "name": "A0HomePageOrg",
    "location": "A0HomePageOrg.html"
}, {
    "name": "D3DeleteProfilePage",
    "location": "D3DeleteProfilePage.html"
}, {
    "name": "H1SubmitNewsPage",
    "location": "H1SubmitNewsPage.html"
}, {
    "name": "L0ContactUsPage",
    "location": "L0ContactUsPage.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "YBridesSonar20170101001",
    "location": "YBridesSonar20170101001.html"
}, {
    "name": "K0HelpPage",
    "location": "K0HelpPage.html"
}, {
    "name": "XAdProfile003",
    "location": "XAdProfile003.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "XAdProfile001",
    "location": "XAdProfile001.html"
}, {
    "name": "A0Homepage",
    "location": "A0Homepage.html"
}, {
    "name": "XAdProfile002",
    "location": "XAdProfile002.html"
}, {
    "name": "ZGroomsSonar20170101003",
    "location": "ZGroomsSonar20170101003.html"
}, {
    "name": "J0TestimonialsPage",
    "location": "J0TestimonialsPage.html"
}, {
    "name": "XAdDialog09",
    "location": "XAdDialog09.html"
}, {
    "name": "ZGroomsSonar20170101001",
    "location": "ZGroomsSonar20170101001.html"
}, {
    "name": "ZGroomsSonar20170101002",
    "location": "ZGroomsSonar20170101002.html"
}, {
    "name": "ZGroomsListPageSonar",
    "location": "ZGroomsListPageSonar.html"
}, {
    "name": "H0NewsPage",
    "location": "H0NewsPage.html"
}, {
    "name": "YBridesListPageSonar",
    "location": "YBridesListPageSonar.html"
}, {
    "name": "G1SubmitEventsPage",
    "location": "G1SubmitEventsPage.html"
}, {
    "name": "L2SubmitSuggestionPage",
    "location": "L2SubmitSuggestionPage.html"
}, {
    "name": "E0DirectoryPage",
    "location": "E0DirectoryPage.html"
}, {
    "name": "G0EventsPage",
    "location": "G0EventsPage.html"
}, {
    "name": "F0ContactsPage",
    "location": "F0ContactsPage.html"
}, {
    "name": "C0SearchSoulmatePage",
    "location": "C0SearchSoulmatePage.html"
}, {
    "name": "D1CreateProfilePage",
    "location": "D1CreateProfilePage.html"
}, {
    "name": "D0RegisterSoulmatePage",
    "location": "D0RegisterSoulmatePage.html"
}, {
    "name": "XAdDialog11",
    "location": "XAdDialog11.html"
}, {
    "name": "XAdDialog10",
    "location": "XAdDialog10.html"
}, {
    "name": "XAdDialog06",
    "location": "XAdDialog06.html"
}, {
    "name": "XAdDialog01",
    "location": "XAdDialog01.html"
}, {
    "name": "I0SocialMediaPage",
    "location": "I0SocialMediaPage.html"
}];

function A0HomePageOrg_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'SettingsButtonName': 'A0HomePageOrg_SettingsButtonName',
        'EnglishGrid1Name': 'A0HomePageOrg_EnglishGrid1Name',
        'EnglishGrid1Cell1': 'A0HomePageOrg_EnglishGrid1Cell1',
        'EnglishSearchSoulmateIconName': 'A0HomePageOrg_EnglishSearchSoulmateIconName',
        'EnglishGrid1Cell2': 'A0HomePageOrg_EnglishGrid1Cell2',
        'EnglishRegisterSoulmateIconName': 'A0HomePageOrg_EnglishRegisterSoulmateIconName',
        'EnglishGrid2Name': 'A0HomePageOrg_EnglishGrid2Name',
        'EnglishGrid2Cell1': 'A0HomePageOrg_EnglishGrid2Cell1',
        'EnglishAboutUsIconName': 'A0HomePageOrg_EnglishAboutUsIconName',
        'EnglishGrid2Cell2': 'A0HomePageOrg_EnglishGrid2Cell2',
        'EnglishDirectoryIconName': 'A0HomePageOrg_EnglishDirectoryIconName',
        'EnglishGrid2Cell3': 'A0HomePageOrg_EnglishGrid2Cell3',
        'EnglishContactsIconName': 'A0HomePageOrg_EnglishContactsIconName',
        'EnglishGrid2Cell4': 'A0HomePageOrg_EnglishGrid2Cell4',
        'EnglishEventsIconName': 'A0HomePageOrg_EnglishEventsIconName',
        'EnglishGrid2Cell5': 'A0HomePageOrg_EnglishGrid2Cell5',
        'EnglishNewsIconName': 'A0HomePageOrg_EnglishNewsIconName',
        'EnglishGrid2Cell6': 'A0HomePageOrg_EnglishGrid2Cell6',
        'EnglishSocialMediaIconName': 'A0HomePageOrg_EnglishSocialMediaIconName',
        'EnglishGrid2Cell7': 'A0HomePageOrg_EnglishGrid2Cell7',
        'EnglishTestmonialsIconName': 'A0HomePageOrg_EnglishTestmonialsIconName',
        'EnglishGrid2Cell8': 'A0HomePageOrg_EnglishGrid2Cell8',
        'EnglishHelpIconName': 'A0HomePageOrg_EnglishHelpIconName',
        'EnglishGrid2Cell9': 'A0HomePageOrg_EnglishGrid2Cell9',
        'EnglishContactUsIconName': 'A0HomePageOrg_EnglishContactUsIconName',
        'EnglishButtonsName': 'A0HomePageOrg_EnglishButtonsName',
        'EnglishAboutUsButtonName': 'A0HomePageOrg_EnglishAboutUsButtonName',
        'EnglishSearchSoulmateButtonName': 'A0HomePageOrg_EnglishSearchSoulmateButtonName',
        'EnglishRegisterSoulmateButtonName': 'A0HomePageOrg_EnglishRegisterSoulmateButtonName',
        'EnglishDirectoryButtonName': 'A0HomePageOrg_EnglishDirectoryButtonName',
        'EnglishContactsButtonName': 'A0HomePageOrg_EnglishContactsButtonName',
        'EnglishEventsButtonName': 'A0HomePageOrg_EnglishEventsButtonName',
        'EnglishNewsButtonName': 'A0HomePageOrg_EnglishNewsButtonName',
        'EnglishSocialMediaButtonName': 'A0HomePageOrg_EnglishSocialMediaButtonName',
        'EnglishTestmonialsButtonName': 'A0HomePageOrg_EnglishTestmonialsButtonName',
        'EnglishHelpButtonName': 'A0HomePageOrg_EnglishHelpButtonName',
        'EnglishContactUsButtonName': 'A0HomePageOrg_EnglishContactUsButtonName',
        'SettingsCollapsBlock': 'A0HomePageOrg_SettingsCollapsBlock',
        'MenuStyleCollapsBlockName': 'A0HomePageOrg_MenuStyleCollapsBlockName',
        'MenuStyleCollapsBlockHeader': 'A0HomePageOrg_MenuStyleCollapsBlockHeader',
        'MenuStyleCollapsBlockContainer': 'A0HomePageOrg_MenuStyleCollapsBlockContainer',
        'MenuStyleIconsButtonName': 'A0HomePageOrg_MenuStyleIconsButtonName',
        'MenuStyleListButtonName': 'A0HomePageOrg_MenuStyleListButtonName',
        'LanguageCollapsBlockName': 'A0HomePageOrg_LanguageCollapsBlockName',
        'LanguageCollapsBlockHeader': 'A0HomePageOrg_LanguageCollapsBlockHeader',
        'LanguageCollapsBlockContainer': 'A0HomePageOrg_LanguageCollapsBlockContainer',
        'LanguageEnglishButtonName': 'A0HomePageOrg_LanguageEnglishButtonName',
        'LanguageMarathiButtonName': 'A0HomePageOrg_LanguageMarathiButtonName',
        'LanguageHindiButtonName': 'A0HomePageOrg_LanguageHindiButtonName',
        'LanguageGujaratiButtonName': 'A0HomePageOrg_LanguageGujaratiButtonName'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'A0HomePageOrg';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var A0HomePageOrg_onLoad = function() {
            A0HomePageOrg_elementsExtraJS();

            var popupElement = Apperyio("");
            if (popupElement.popup("option", "positionTo") === "origin") {
                popupElement.popup("open", {
                    transition: "pop",
                    positionTo: "#" + $(this).attr("id")
                });
            } else {
                popupElement.popup("open", {
                    transition: "pop"
                });
            };

            A0HomePageOrg_deviceEvents();
            A0HomePageOrg_windowEvents();
            A0HomePageOrg_elementsEvents();
        };

    // screen window events


    function A0HomePageOrg_windowEvents() {

        $('#A0HomePageOrg').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function A0HomePageOrg_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function A0HomePageOrg_elementsExtraJS() {
        // screen (A0HomePageOrg) extra code

        /* SettingsPopupName */
        $("#A0HomePageOrg_SettingsPopupName").popup("option", "positionTo", "window");

        /* MenuStyleCollapsBlockName */

        $("#A0HomePageOrg_MenuStyleCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "21");

        /* LanguageCollapsBlockName */

        $("#A0HomePageOrg_LanguageCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "21");

    };

    // screen elements handler


    function A0HomePageOrg_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#A0HomePageOrg_A0HomeHeaderName [name="SettingsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("SettingsPopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#A0HomePageOrg_A0HomeHeaderName [name="SettingsButtonName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishSearchSoulmateIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('C0SearchSoulmatePage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog02', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishSearchSoulmateIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishRegisterSoulmateIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('D0RegisterSoulmatePage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog03', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishRegisterSoulmateIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishAboutUsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('B0AboutUsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog01', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishAboutUsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishDirectoryIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('E0DirectoryPage', {
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog04', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishDirectoryIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('F0ContactsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog05', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishEventsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('G0EventsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog06', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishEventsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishNewsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('H0NewsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog07', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishNewsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishSocialMediaIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('I0SocialMediaPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog08', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishSocialMediaIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishTestmonialsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('J0TestimonialsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog09', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishTestmonialsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishHelpIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('K0HelpPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog10', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishHelpIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactUsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('L0ContactUsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog11', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactUsIconName"]');

        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishAboutUsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('B0AboutUsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog01', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishAboutUsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishSearchSoulmateButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('C0SearchSoulmatePage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog02', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishSearchSoulmateButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishRegisterSoulmateButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('D0RegisterSoulmatePage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog03', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishRegisterSoulmateButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishDirectoryButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('E0DirectoryPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog04', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishDirectoryButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('F0ContactsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog05', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishEventsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('G0EventsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog06', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishEventsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishNewsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('H0NewsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog07', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishNewsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishSocialMediaButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('I0SocialMediaPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog08', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishSocialMediaButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishTestmonialsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('J0TestimonialsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog09', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishTestmonialsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishHelpButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('K0HelpPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog10', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishHelpButtonName"]');
        $(document).off("click", '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactUsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('L0ContactUsPage', {
                        transition: 'slide',
                        reverse: false
                    });
                    Apperyio.navigateTo('XAdDialog11', {
                        transition: 'pop'
                    });

                }
            },
        }, '#A0HomePageOrg_A0HomeContainerName [name="EnglishContactUsButtonName"]');

        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="MenuStyleIconsButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('A0HomePageOrg_EnglishButtonsName', 'mob', 'false');
                    toggle('A0HomePageOrg_EnglishGrid1Name', 'mob', 'true');
                    toggle('A0HomePageOrg_EnglishGrid2Name', 'mob', 'true');
                    try {
                        $a.c15r("SettingsButtonName", "set", "text", 'Icons')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="MenuStyleIconsButtonName"]');
        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="MenuStyleListButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    toggle('A0HomePageOrg_EnglishGrid1Name', 'mob', 'false');
                    toggle('A0HomePageOrg_EnglishGrid2Name', 'mob', 'false');
                    toggle('A0HomePageOrg_EnglishButtonsName', 'mob', 'true');
                    try {
                        $a.c15r("SettingsButtonName", "set", "text", 'List')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="MenuStyleListButtonName"]');

        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="LanguageEnglishButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("EnglishAboutUsButtonName", "set", "text", 'About Us')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishAboutUsIconName', 'src', '../img/englishaboutusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishAboutUsIconName"]').refresh();
                    setAttribute_('A0HomePageOrg_EnglishContactsIconName', 'src', '../img/englishcontactsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactsButtonName", "set", "text", 'Contacts')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("EnglishContactUsButtonName", "set", "text", 'Contact Us')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactUsIconName', 'src', '../img/englishcontactusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishDirectoryButtonName", "set", "text", 'Directory')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishDirectoryIconName', 'src', '../img/englishdirectorybuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishDirectoryIconName"]').refresh();
                    try {
                        $a.c15r("EnglishEventsButtonName", "set", "text", 'Events')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishEventsIconName', 'src', '../img/englisheventsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishEventsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishHelpButtonName", "set", "text", 'Help')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishHelpIconName', 'src', '../img/englishhelpbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishHelpIconName"]').refresh();
                    try {
                        $a.c15r("EnglishNewsButtonName", "set", "text", 'News')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishNewsIconName', 'src', '../img/englishnewsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishNewsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishRegisterSoulmateButtonName", "set", "text", 'Register Soulmate')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishRegisterSoulmateIconName', 'src', '../img/englishregistersoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishRegisterSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSearchSoulmateButtonName", "set", "text", 'Search Soulmate')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSearchSoulmateIconName', 'src', '../img/englishsearchsoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSearchSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSocialMediaButtonName", "set", "text", 'Social Media')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSocialMediaIconName', 'src', '../img/englishsocialmediabuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSocialMediaIconName"]').refresh();
                    try {
                        $a.c15r("EnglishTestmonialsButtonName", "set", "text", 'Testmonials')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishTestmonialsIconName', 'src', '../img/englishtestmoinalsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishTestmonialsIconName"]').refresh();
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="LanguageEnglishButtonName"]');
        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="LanguageMarathiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("EnglishAboutUsButtonName", "set", "text", 'आमच्या विषयी')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishAboutUsIconName', 'src', '../img/marathiaboutusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishAboutUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactsButtonName", "set", "text", 'Contacts - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactsIconName', 'src', '../img/marathicontactsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactUsButtonName", "set", "text", 'Contact Us - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactUsIconName', 'src', '../img/marathicontactusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishDirectoryButtonName", "set", "text", 'Directory - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishDirectoryIconName', 'src', '../img/marathidirectorybuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishDirectoryIconName"]').refresh();
                    try {
                        $a.c15r("EnglishEventsButtonName", "set", "text", 'Events - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishEventsIconName', 'src', '../img/marathieventsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishEventsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishHelpButtonName", "set", "text", 'Help - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishHelpIconName', 'src', '../img/marathihelpbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishHelpIconName"]').refresh();
                    try {
                        $a.c15r("EnglishNewsButtonName", "set", "text", 'News - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishNewsIconName', 'src', '../img/marathinewsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishNewsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishRegisterSoulmateButtonName", "set", "text", 'Register Soulmate - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishRegisterSoulmateIconName', 'src', '../img/marathiregistersoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishRegisterSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSearchSoulmateButtonName", "set", "text", 'Search Soulmate - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSearchSoulmateIconName', 'src', '../img/marathisearchsoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSearchSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSocialMediaButtonName", "set", "text", 'Social Media - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSocialMediaIconName', 'src', '../img/marathisocialmediabuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSocialMediaIconName"]').refresh();
                    try {
                        $a.c15r("EnglishTestmonialsButtonName", "set", "text", 'Testmonials - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishTestmonialsIconName', 'src', '../img/marathitestmoinalsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishTestmonialsIconName"]').refresh();
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="LanguageMarathiButtonName"]');
        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="LanguageHindiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("EnglishAboutUsButtonName", "set", "text", 'हमारे बारे में')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishAboutUsIconName', 'src', '../img/hindiaboutusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishAboutUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactsButtonName", "set", "text", 'Contacts - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactsIconName', 'src', '../img/hindicontactsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactUsButtonName", "set", "text", 'Contact Us - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactUsIconName', 'src', '../img/hindicontactusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishDirectoryButtonName", "set", "text", 'Directory - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishDirectoryIconName', 'src', '../img/hindidirectorybuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishDirectoryIconName"]').refresh();
                    try {
                        $a.c15r("EnglishEventsButtonName", "set", "text", 'Events - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishEventsIconName', 'src', '../img/hindieventsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishEventsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishHelpButtonName", "set", "text", 'Help - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishHelpIconName', 'src', '../img/hindihelpbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishHelpIconName"]').refresh();
                    try {
                        $a.c15r("EnglishNewsButtonName", "set", "text", 'News - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishNewsIconName', 'src', '../img/hindinewsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishNewsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishRegisterSoulmateButtonName", "set", "text", 'Register Soulmate - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishRegisterSoulmateIconName', 'src', '../img/hindiregistersoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishRegisterSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSearchSoulmateButtonName", "set", "text", 'Search Soulmate - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSearchSoulmateIconName', 'src', '../img/hindisearchsoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSearchSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSocialMediaButtonName", "set", "text", 'Social Media - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSocialMediaIconName', 'src', '../img/hindisocialmediabuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSocialMediaIconName"]').refresh();
                    try {
                        $a.c15r("EnglishTestmonialsButtonName", "set", "text", 'Testmonials - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishTestmonialsIconName', 'src', '../img/hinditestmoinalsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishTestmonialsIconName"]').refresh();
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="LanguageHindiButtonName"]');
        $(document).off("click", '#A0HomePageOrg_SettingsPopupName [name="LanguageGujaratiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("EnglishAboutUsButtonName", "set", "text", 'અમારા વિશે')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishAboutUsIconName', 'src', '../img/gujaratiaboutusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishAboutUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactsButtonName", "set", "text", 'Contacts - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactsIconName', 'src', '../img/gujaraticontactsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishContactUsButtonName", "set", "text", 'Contact Us - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishContactUsIconName', 'src', '../img/gujaraticontactusbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishContactUsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishDirectoryButtonName", "set", "text", 'Directory - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishDirectoryIconName', 'src', '../img/gujaratidirectorybuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishDirectoryIconName"]').refresh();
                    try {
                        $a.c15r("EnglishEventsButtonName", "set", "text", 'Events - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishEventsIconName', 'src', '../img/gujaratieventsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishEventsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishHelpButtonName", "set", "text", 'Help - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishHelpIconName', 'src', '../img/gujaratihelpbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishHelpIconName"]').refresh();
                    try {
                        $a.c15r("EnglishNewsButtonName", "set", "text", 'News - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishNewsIconName', 'src', '../img/gujaratinewsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishNewsIconName"]').refresh();
                    try {
                        $a.c15r("EnglishRegisterSoulmateButtonName", "set", "text", 'Register Soulmate - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishRegisterSoulmateIconName', 'src', '../img/gujaratiregistersoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishRegisterSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSearchSoulmateButtonName", "set", "text", 'Search Soulmate - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSearchSoulmateIconName', 'src', '../img/gujaratisearchsoulmatebuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSearchSoulmateIconName"]').refresh();
                    try {
                        $a.c15r("EnglishSocialMediaButtonName", "set", "text", 'Social Media - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishSocialMediaIconName', 'src', '../img/gujaratisocialmediabuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishSocialMediaIconName"]').refresh();
                    try {
                        $a.c15r("EnglishTestmonialsButtonName", "set", "text", 'Testmonials - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('A0HomePageOrg_EnglishTestmonialsIconName', 'src', '../img/gujaratitestmoinalsbuttonimage.png');
                    $('[id="A0HomePageOrg_EnglishTestmonialsIconName"]').refresh();
                    Apperyio('SettingsPopupName').popup('close');
                    Apperyio('SettingsPopupName').popup('close');

                }
            },
        }, '#A0HomePageOrg_SettingsPopupName [name="LanguageGujaratiButtonName"]');

    };

    $(document).off("pagebeforeshow", "#A0HomePageOrg").on("pagebeforeshow", "#A0HomePageOrg", function(event, ui) {
        Apperyio.CurrentScreen = "A0HomePageOrg";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    A0HomePageOrg_onLoad();
};

$(document).off("pagecreate", "#A0HomePageOrg").on("pagecreate", "#A0HomePageOrg", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    A0HomePageOrg_js();
});