/*
 * JS for C0SearchSoulmatePage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ac2f1913-e4fd-4043-aae9-c940ec4861d1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "L1SubmitAdvertisingPage",
    "location": "L1SubmitAdvertisingPage.html"
}, {
    "name": "XAdDialog07",
    "location": "XAdDialog07.html"
}, {
    "name": "XAdDialog05",
    "location": "XAdDialog05.html"
}, {
    "name": "XAdDialog08",
    "location": "XAdDialog08.html"
}, {
    "name": "XAdDialog03",
    "location": "XAdDialog03.html"
}, {
    "name": "XAdDialog02",
    "location": "XAdDialog02.html"
}, {
    "name": "L3TermsandConditionsPage",
    "location": "L3TermsandConditionsPage.html"
}, {
    "name": "XAdDialog04",
    "location": "XAdDialog04.html"
}, {
    "name": "YBridesSonar20170101002",
    "location": "YBridesSonar20170101002.html"
}, {
    "name": "YBridesSonar20170101003",
    "location": "YBridesSonar20170101003.html"
}, {
    "name": "D2EditProfilePage",
    "location": "D2EditProfilePage.html"
}, {
    "name": "L4DeveloperPage",
    "location": "L4DeveloperPage.html"
}, {
    "name": "J1SubmitTestimonialsPage",
    "location": "J1SubmitTestimonialsPage.html"
}, {
    "name": "B0AboutUsPage",
    "location": "B0AboutUsPage.html"
}, {
    "name": "A0HomePageOrg",
    "location": "A0HomePageOrg.html"
}, {
    "name": "D3DeleteProfilePage",
    "location": "D3DeleteProfilePage.html"
}, {
    "name": "H1SubmitNewsPage",
    "location": "H1SubmitNewsPage.html"
}, {
    "name": "L0ContactUsPage",
    "location": "L0ContactUsPage.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "YBridesSonar20170101001",
    "location": "YBridesSonar20170101001.html"
}, {
    "name": "K0HelpPage",
    "location": "K0HelpPage.html"
}, {
    "name": "XAdProfile003",
    "location": "XAdProfile003.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "XAdProfile001",
    "location": "XAdProfile001.html"
}, {
    "name": "A0Homepage",
    "location": "A0Homepage.html"
}, {
    "name": "XAdProfile002",
    "location": "XAdProfile002.html"
}, {
    "name": "ZGroomsSonar20170101003",
    "location": "ZGroomsSonar20170101003.html"
}, {
    "name": "J0TestimonialsPage",
    "location": "J0TestimonialsPage.html"
}, {
    "name": "XAdDialog09",
    "location": "XAdDialog09.html"
}, {
    "name": "ZGroomsSonar20170101001",
    "location": "ZGroomsSonar20170101001.html"
}, {
    "name": "ZGroomsSonar20170101002",
    "location": "ZGroomsSonar20170101002.html"
}, {
    "name": "ZGroomsListPageSonar",
    "location": "ZGroomsListPageSonar.html"
}, {
    "name": "H0NewsPage",
    "location": "H0NewsPage.html"
}, {
    "name": "YBridesListPageSonar",
    "location": "YBridesListPageSonar.html"
}, {
    "name": "G1SubmitEventsPage",
    "location": "G1SubmitEventsPage.html"
}, {
    "name": "L2SubmitSuggestionPage",
    "location": "L2SubmitSuggestionPage.html"
}, {
    "name": "E0DirectoryPage",
    "location": "E0DirectoryPage.html"
}, {
    "name": "G0EventsPage",
    "location": "G0EventsPage.html"
}, {
    "name": "F0ContactsPage",
    "location": "F0ContactsPage.html"
}, {
    "name": "C0SearchSoulmatePage",
    "location": "C0SearchSoulmatePage.html"
}, {
    "name": "D1CreateProfilePage",
    "location": "D1CreateProfilePage.html"
}, {
    "name": "D0RegisterSoulmatePage",
    "location": "D0RegisterSoulmatePage.html"
}, {
    "name": "XAdDialog11",
    "location": "XAdDialog11.html"
}, {
    "name": "XAdDialog10",
    "location": "XAdDialog10.html"
}, {
    "name": "XAdDialog06",
    "location": "XAdDialog06.html"
}, {
    "name": "XAdDialog01",
    "location": "XAdDialog01.html"
}, {
    "name": "I0SocialMediaPage",
    "location": "I0SocialMediaPage.html"
}];

function C0SearchSoulmatePage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'LanguageButtonName': 'C0SearchSoulmatePage_LanguageButtonName',
        'SearchSoulmateCollapsibleSetName': 'C0SearchSoulmatePage_SearchSoulmateCollapsibleSetName',
        'SonarCollapsBlockName': 'C0SearchSoulmatePage_SonarCollapsBlockName',
        'SonarCollapsBlockHeader': 'C0SearchSoulmatePage_SonarCollapsBlockHeader',
        'SonarCollapsBlockContainer': 'C0SearchSoulmatePage_SonarCollapsBlockContainer',
        'EnglishSonarGridName': 'C0SearchSoulmatePage_EnglishSonarGridName',
        'EnglishSonarGridCell1Name': 'C0SearchSoulmatePage_EnglishSonarGridCell1Name',
        'EnglishSonarBridesIconName': 'C0SearchSoulmatePage_EnglishSonarBridesIconName',
        'EnglishSonarGridCell2Name': 'C0SearchSoulmatePage_EnglishSonarGridCell2Name',
        'EnglishSonarGroomsIconName': 'C0SearchSoulmatePage_EnglishSonarGroomsIconName',
        'OthersCollapsBlockName': 'C0SearchSoulmatePage_OthersCollapsBlockName',
        'OthersCollapsBlockHeader': 'C0SearchSoulmatePage_OthersCollapsBlockHeader',
        'OthersCollapsBlockContainer': 'C0SearchSoulmatePage_OthersCollapsBlockContainer',
        'PopupLable1Name': 'C0SearchSoulmatePage_PopupLable1Name',
        'PopupLable2Name': 'C0SearchSoulmatePage_PopupLable2Name',
        'PopupLable3Name': 'C0SearchSoulmatePage_PopupLable3Name',
        'LanguageEnglishButtonName': 'C0SearchSoulmatePage_LanguageEnglishButtonName',
        'LanguageMarathiButtonName': 'C0SearchSoulmatePage_LanguageMarathiButtonName',
        'LanguageHindiButtonName': 'C0SearchSoulmatePage_LanguageHindiButtonName',
        'LanguageGujaratiButtonName': 'C0SearchSoulmatePage_LanguageGujaratiButtonName'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'C0SearchSoulmatePage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var C0SearchSoulmatePage_onLoad = function() {
            C0SearchSoulmatePage_elementsExtraJS();

            C0SearchSoulmatePage_deviceEvents();
            C0SearchSoulmatePage_windowEvents();
            C0SearchSoulmatePage_elementsEvents();
        };

    // screen window events


    function C0SearchSoulmatePage_windowEvents() {

        $('#C0SearchSoulmatePage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#C0SearchSoulmatePage').on({
            pageshow: function(event) {
                var popupElement = Apperyio("C0SearchSoulmatePopup");
                if (popupElement.popup("option", "positionTo") === "origin") {
                    popupElement.popup("open", {
                        transition: "pop",
                        positionTo: "#" + $(this).attr("id")
                    });
                } else {
                    popupElement.popup("open", {
                        transition: "pop"
                    });
                };
            },
        });

    };

    // device events


    function C0SearchSoulmatePage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function C0SearchSoulmatePage_elementsExtraJS() {
        // screen (C0SearchSoulmatePage) extra code

        /* SonarCollapsBlockName */

        $("#C0SearchSoulmatePage_SonarCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* OthersCollapsBlockName */

        $("#C0SearchSoulmatePage_OthersCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* C0SearchSoulmatePopup */
        $("#C0SearchSoulmatePage_C0SearchSoulmatePopup").popup("option", "positionTo", "window");

        /* LanguagePopupName */
        $("#C0SearchSoulmatePage_LanguagePopupName").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function C0SearchSoulmatePage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#C0SearchSoulmatePage_C0SearchSoulmateHeaderName [name="LanguageButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("LanguagePopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#C0SearchSoulmatePage_C0SearchSoulmateHeaderName [name="LanguageButtonName"]');

        $(document).off("click", '#C0SearchSoulmatePage_C0SearchSoulmateContainerName [name="EnglishSonarBridesIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('YBridesListPageSonar', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#C0SearchSoulmatePage_C0SearchSoulmateContainerName [name="EnglishSonarBridesIconName"]');

        $(document).off("click", '#C0SearchSoulmatePage_C0SearchSoulmateContainerName [name="EnglishSonarGroomsIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ZGroomsListPageSonar', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#C0SearchSoulmatePage_C0SearchSoulmateContainerName [name="EnglishSonarGroomsIconName"]');

        $(document).off("click", '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageEnglishButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("C0SearchSoulmateHeaderName", "set", "text", 'Search Soulmate')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("LanguageButtonName", "set", "text", 'English')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("SonarCollapsBlockHeader", "set", "text", 'Sonar')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarBridesIconName', 'src', '../img/englishbridesbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarBridesIconName"]').refresh();
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarGroomsIconName', 'src', '../img/englishgroomsbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarGroomsIconName"]').refresh();
                    try {
                        $a.c15r("OthersCollapsBlockHeader", "set", "text", 'Others')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('LanguagePopupName').popup('close');

                }
            },
        }, '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageEnglishButtonName"]');
        $(document).off("click", '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageMarathiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("C0SearchSoulmateHeaderName", "set", "text", 'Search Soulmate - Marathi')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("LanguageButtonName", "set", "text", 'मराठी')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("SonarCollapsBlockHeader", "set", "text", 'सोनार')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarBridesIconName', 'src', '../img/marathibridesbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarBridesIconName"]').refresh();
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarGroomsIconName', 'src', '../img/marathigroomsbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarGroomsIconName"]').refresh();
                    try {
                        $a.c15r("OthersCollapsBlockHeader", "set", "text", 'इतर')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('LanguagePopupName').popup('close');

                }
            },
        }, '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageMarathiButtonName"]');
        $(document).off("click", '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageHindiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("C0SearchSoulmateHeaderName", "set", "text", 'Search Soulmate - Hindi')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("LanguageButtonName", "set", "text", 'हिंदी')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("SonarCollapsBlockHeader", "set", "text", 'सोनार')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarBridesIconName', 'src', '../img/hindibridesbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarBridesIconName"]').refresh();
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarGroomsIconName', 'src', '../img/hindigroomsbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarGroomsIconName"]').refresh();
                    try {
                        $a.c15r("OthersCollapsBlockHeader", "set", "text", 'अन्य')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('LanguagePopupName').popup('close');

                }
            },
        }, '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageHindiButtonName"]');
        $(document).off("click", '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageGujaratiButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.c15r("C0SearchSoulmateHeaderName", "set", "text", 'Search Soulmate - Gujarati')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("LanguageButtonName", "set", "text", 'ગુજરાતી')
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.c15r("SonarCollapsBlockHeader", "set", "text", 'સોનાર')
                    } catch (e) {
                        console.error(e)
                    };
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarBridesIconName', 'src', '../img/gujaratibridesbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarBridesIconName"]').refresh();
                    setAttribute_('C0SearchSoulmatePage_EnglishSonarGroomsIconName', 'src', '../img/gujaratigroomsbuttonimage.png');
                    $('[id="C0SearchSoulmatePage_EnglishSonarGroomsIconName"]').refresh();
                    try {
                        $a.c15r("OthersCollapsBlockHeader", "set", "text", 'અન્ય')
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio('LanguagePopupName').popup('close');

                }
            },
        }, '#C0SearchSoulmatePage_LanguagePopupName [name="LanguageGujaratiButtonName"]');

    };

    $(document).off("pagebeforeshow", "#C0SearchSoulmatePage").on("pagebeforeshow", "#C0SearchSoulmatePage", function(event, ui) {
        Apperyio.CurrentScreen = "C0SearchSoulmatePage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    C0SearchSoulmatePage_onLoad();
};

$(document).off("pagecreate", "#C0SearchSoulmatePage").on("pagecreate", "#C0SearchSoulmatePage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    C0SearchSoulmatePage_js();
});