/*
 * JS for ExamplePage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ac2f1913-e4fd-4043-aae9-c940ec4861d1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "L1SubmitAdvertisingPage",
    "location": "L1SubmitAdvertisingPage.html"
}, {
    "name": "XAdDialog07",
    "location": "XAdDialog07.html"
}, {
    "name": "XAdDialog05",
    "location": "XAdDialog05.html"
}, {
    "name": "XAdDialog08",
    "location": "XAdDialog08.html"
}, {
    "name": "XAdDialog03",
    "location": "XAdDialog03.html"
}, {
    "name": "XAdDialog02",
    "location": "XAdDialog02.html"
}, {
    "name": "L3TermsandConditionsPage",
    "location": "L3TermsandConditionsPage.html"
}, {
    "name": "XAdDialog04",
    "location": "XAdDialog04.html"
}, {
    "name": "YBridesSonar20170101002",
    "location": "YBridesSonar20170101002.html"
}, {
    "name": "YBridesSonar20170101003",
    "location": "YBridesSonar20170101003.html"
}, {
    "name": "D2EditProfilePage",
    "location": "D2EditProfilePage.html"
}, {
    "name": "L4DeveloperPage",
    "location": "L4DeveloperPage.html"
}, {
    "name": "J1SubmitTestimonialsPage",
    "location": "J1SubmitTestimonialsPage.html"
}, {
    "name": "B0AboutUsPage",
    "location": "B0AboutUsPage.html"
}, {
    "name": "A0HomePageOrg",
    "location": "A0HomePageOrg.html"
}, {
    "name": "D3DeleteProfilePage",
    "location": "D3DeleteProfilePage.html"
}, {
    "name": "H1SubmitNewsPage",
    "location": "H1SubmitNewsPage.html"
}, {
    "name": "L0ContactUsPage",
    "location": "L0ContactUsPage.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "YBridesSonar20170101001",
    "location": "YBridesSonar20170101001.html"
}, {
    "name": "K0HelpPage",
    "location": "K0HelpPage.html"
}, {
    "name": "XAdProfile003",
    "location": "XAdProfile003.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "XAdProfile001",
    "location": "XAdProfile001.html"
}, {
    "name": "A0Homepage",
    "location": "A0Homepage.html"
}, {
    "name": "XAdProfile002",
    "location": "XAdProfile002.html"
}, {
    "name": "ZGroomsSonar20170101003",
    "location": "ZGroomsSonar20170101003.html"
}, {
    "name": "J0TestimonialsPage",
    "location": "J0TestimonialsPage.html"
}, {
    "name": "XAdDialog09",
    "location": "XAdDialog09.html"
}, {
    "name": "ZGroomsSonar20170101001",
    "location": "ZGroomsSonar20170101001.html"
}, {
    "name": "ZGroomsSonar20170101002",
    "location": "ZGroomsSonar20170101002.html"
}, {
    "name": "ZGroomsListPageSonar",
    "location": "ZGroomsListPageSonar.html"
}, {
    "name": "H0NewsPage",
    "location": "H0NewsPage.html"
}, {
    "name": "YBridesListPageSonar",
    "location": "YBridesListPageSonar.html"
}, {
    "name": "G1SubmitEventsPage",
    "location": "G1SubmitEventsPage.html"
}, {
    "name": "L2SubmitSuggestionPage",
    "location": "L2SubmitSuggestionPage.html"
}, {
    "name": "E0DirectoryPage",
    "location": "E0DirectoryPage.html"
}, {
    "name": "G0EventsPage",
    "location": "G0EventsPage.html"
}, {
    "name": "F0ContactsPage",
    "location": "F0ContactsPage.html"
}, {
    "name": "C0SearchSoulmatePage",
    "location": "C0SearchSoulmatePage.html"
}, {
    "name": "D1CreateProfilePage",
    "location": "D1CreateProfilePage.html"
}, {
    "name": "D0RegisterSoulmatePage",
    "location": "D0RegisterSoulmatePage.html"
}, {
    "name": "XAdDialog11",
    "location": "XAdDialog11.html"
}, {
    "name": "XAdDialog10",
    "location": "XAdDialog10.html"
}, {
    "name": "XAdDialog06",
    "location": "XAdDialog06.html"
}, {
    "name": "XAdDialog01",
    "location": "XAdDialog01.html"
}, {
    "name": "I0SocialMediaPage",
    "location": "I0SocialMediaPage.html"
}];

function ExamplePage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'ExamplePage_mobilebutton_2',
        'mobilebutton_3': 'ExamplePage_mobilebutton_3',
        'mobiletextinput_4': 'ExamplePage_mobiletextinput_4',
        'mobiledatepicker_5': 'ExamplePage_mobiledatepicker_5',
        'mobilebutton_6': 'ExamplePage_mobilebutton_6',
        'mobiletoggle_12': 'ExamplePage_mobiletoggle_12',
        'mobileslider_11': 'ExamplePage_mobileslider_11',
        'mobilelist_13': 'ExamplePage_mobilelist_13',
        'mobilelistitem_14': 'ExamplePage_mobilelistitem_14',
        'mobilelistitembutton_15': 'ExamplePage_mobilelistitembutton_15',
        'mobilelistitem_16': 'ExamplePage_mobilelistitem_16',
        'mobilelistitembutton_17': 'ExamplePage_mobilelistitembutton_17',
        'mobilelistitem_18': 'ExamplePage_mobilelistitem_18',
        'mobilelistitembutton_19': 'ExamplePage_mobilelistitembutton_19',
        'mobilecheckboxgroup_7': 'ExamplePage_mobilecheckboxgroup_7',
        'mobilecheckbox_8': 'ExamplePage_mobilecheckbox_8',
        'mobilecheckbox_9': 'ExamplePage_mobilecheckbox_9',
        'mobilenavbar_20': 'ExamplePage_mobilenavbar_20',
        'mobilenavbaritem_21': 'ExamplePage_mobilenavbaritem_21',
        'mobilenavbaritem_22': 'ExamplePage_mobilenavbaritem_22',
        'mobilenavbaritem_23': 'ExamplePage_mobilenavbaritem_23'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ExamplePage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ExamplePage_onLoad = function() {
            ExamplePage_elementsExtraJS();

            ExamplePage_deviceEvents();
            ExamplePage_windowEvents();
            ExamplePage_elementsEvents();
        };

    // screen window events


    function ExamplePage_windowEvents() {

        $('#ExamplePage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ExamplePage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ExamplePage_elementsExtraJS() {
        // screen (ExamplePage) extra code

        /* mobiledatepicker_5 */

        ExamplePage_mobiledatepicker_5_selector = "#ExamplePage_mobiledatepicker_5";
        ExamplePage_mobiledatepicker_5_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        ExamplePage_mobiledatepicker_5_dataPickerOptions.defaultDate = new Date("10/21/2014");

        Apperyio.__registerComponent('mobiledatepicker_5', new Apperyio.ApperyMobileDatePickerComponent("ExamplePage_mobiledatepicker_5", ExamplePage_mobiledatepicker_5_dataPickerOptions));

        /* mobiletoggle_12 */

        $("#ExamplePage_mobiletoggle_12").parent().find(".ui-flipswitch-on").attr("tabindex", "8");

        /* mobilelist_13 */

        listView = $("#ExamplePage_mobilelist_13");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ExamplePage_mobilelist_13 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_14 */

        /* mobilelistitem_16 */

        /* mobilelistitem_18 */

    };

    // screen elements handler


    function ExamplePage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#ExamplePage").on("pagebeforeshow", "#ExamplePage", function(event, ui) {
        Apperyio.CurrentScreen = "ExamplePage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ExamplePage_onLoad();
};

$(document).off("pagecreate", "#ExamplePage").on("pagecreate", "#ExamplePage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ExamplePage_js();
});