/*
 * JS for L4DeveloperPage generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ac2f1913-e4fd-4043-aae9-c940ec4861d1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "L1SubmitAdvertisingPage",
    "location": "L1SubmitAdvertisingPage.html"
}, {
    "name": "XAdDialog07",
    "location": "XAdDialog07.html"
}, {
    "name": "XAdDialog05",
    "location": "XAdDialog05.html"
}, {
    "name": "XAdDialog08",
    "location": "XAdDialog08.html"
}, {
    "name": "XAdDialog03",
    "location": "XAdDialog03.html"
}, {
    "name": "XAdDialog02",
    "location": "XAdDialog02.html"
}, {
    "name": "L3TermsandConditionsPage",
    "location": "L3TermsandConditionsPage.html"
}, {
    "name": "XAdDialog04",
    "location": "XAdDialog04.html"
}, {
    "name": "YBridesSonar20170101002",
    "location": "YBridesSonar20170101002.html"
}, {
    "name": "YBridesSonar20170101003",
    "location": "YBridesSonar20170101003.html"
}, {
    "name": "D2EditProfilePage",
    "location": "D2EditProfilePage.html"
}, {
    "name": "L4DeveloperPage",
    "location": "L4DeveloperPage.html"
}, {
    "name": "J1SubmitTestimonialsPage",
    "location": "J1SubmitTestimonialsPage.html"
}, {
    "name": "B0AboutUsPage",
    "location": "B0AboutUsPage.html"
}, {
    "name": "A0HomePageOrg",
    "location": "A0HomePageOrg.html"
}, {
    "name": "D3DeleteProfilePage",
    "location": "D3DeleteProfilePage.html"
}, {
    "name": "H1SubmitNewsPage",
    "location": "H1SubmitNewsPage.html"
}, {
    "name": "L0ContactUsPage",
    "location": "L0ContactUsPage.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "YBridesSonar20170101001",
    "location": "YBridesSonar20170101001.html"
}, {
    "name": "K0HelpPage",
    "location": "K0HelpPage.html"
}, {
    "name": "XAdProfile003",
    "location": "XAdProfile003.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "XAdProfile001",
    "location": "XAdProfile001.html"
}, {
    "name": "A0Homepage",
    "location": "A0Homepage.html"
}, {
    "name": "XAdProfile002",
    "location": "XAdProfile002.html"
}, {
    "name": "ZGroomsSonar20170101003",
    "location": "ZGroomsSonar20170101003.html"
}, {
    "name": "J0TestimonialsPage",
    "location": "J0TestimonialsPage.html"
}, {
    "name": "XAdDialog09",
    "location": "XAdDialog09.html"
}, {
    "name": "ZGroomsSonar20170101001",
    "location": "ZGroomsSonar20170101001.html"
}, {
    "name": "ZGroomsSonar20170101002",
    "location": "ZGroomsSonar20170101002.html"
}, {
    "name": "ZGroomsListPageSonar",
    "location": "ZGroomsListPageSonar.html"
}, {
    "name": "H0NewsPage",
    "location": "H0NewsPage.html"
}, {
    "name": "YBridesListPageSonar",
    "location": "YBridesListPageSonar.html"
}, {
    "name": "G1SubmitEventsPage",
    "location": "G1SubmitEventsPage.html"
}, {
    "name": "L2SubmitSuggestionPage",
    "location": "L2SubmitSuggestionPage.html"
}, {
    "name": "E0DirectoryPage",
    "location": "E0DirectoryPage.html"
}, {
    "name": "G0EventsPage",
    "location": "G0EventsPage.html"
}, {
    "name": "F0ContactsPage",
    "location": "F0ContactsPage.html"
}, {
    "name": "C0SearchSoulmatePage",
    "location": "C0SearchSoulmatePage.html"
}, {
    "name": "D1CreateProfilePage",
    "location": "D1CreateProfilePage.html"
}, {
    "name": "D0RegisterSoulmatePage",
    "location": "D0RegisterSoulmatePage.html"
}, {
    "name": "XAdDialog11",
    "location": "XAdDialog11.html"
}, {
    "name": "XAdDialog10",
    "location": "XAdDialog10.html"
}, {
    "name": "XAdDialog06",
    "location": "XAdDialog06.html"
}, {
    "name": "XAdDialog01",
    "location": "XAdDialog01.html"
}, {
    "name": "I0SocialMediaPage",
    "location": "I0SocialMediaPage.html"
}];

function L4DeveloperPage_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'L4DeveloperLableName': 'L4DeveloperPage_L4DeveloperLableName',
        'L4DeveloperGridName': 'L4DeveloperPage_L4DeveloperGridName',
        'L4DeveloperGridCell1Name': 'L4DeveloperPage_L4DeveloperGridCell1Name',
        'FacebookIconName': 'L4DeveloperPage_FacebookIconName',
        'L4DeveloperGridCell2Name': 'L4DeveloperPage_L4DeveloperGridCell2Name',
        'TwitterIconName': 'L4DeveloperPage_TwitterIconName',
        'L4DeveloperGridCell3Name': 'L4DeveloperPage_L4DeveloperGridCell3Name',
        'InstagramIconName': 'L4DeveloperPage_InstagramIconName',
        'PopupLable1Name': 'L4DeveloperPage_PopupLable1Name',
        'FacebookPoopupLable1Name': 'L4DeveloperPage_FacebookPoopupLable1Name',
        'TwitterPoopupLable1Name': 'L4DeveloperPage_TwitterPoopupLable1Name',
        'InstagramPoopupLable1Name': 'L4DeveloperPage_InstagramPoopupLable1Name'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'L4DeveloperPage';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var L4DeveloperPage_onLoad = function() {
            L4DeveloperPage_elementsExtraJS();

            L4DeveloperPage_deviceEvents();
            L4DeveloperPage_windowEvents();
            L4DeveloperPage_elementsEvents();
        };

    // screen window events


    function L4DeveloperPage_windowEvents() {

        $('#L4DeveloperPage').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#L4DeveloperPage').on({
            pageshow: function(event) {
                var popupElement = Apperyio("L4DeveloperPopupName");
                if (popupElement.popup("option", "positionTo") === "origin") {
                    popupElement.popup("open", {
                        transition: "pop",
                        positionTo: "#" + $(this).attr("id")
                    });
                } else {
                    popupElement.popup("open", {
                        transition: "pop"
                    });
                };
            },
        });

    };

    // device events


    function L4DeveloperPage_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function L4DeveloperPage_elementsExtraJS() {
        // screen (L4DeveloperPage) extra code

        /* L4DeveloperPopupName */
        $("#L4DeveloperPage_L4DeveloperPopupName").popup("option", "positionTo", "window");

        /* FacebookPopupName */
        $("#L4DeveloperPage_FacebookPopupName").popup("option", "positionTo", "window");

        /* TwitterPopupName */
        $("#L4DeveloperPage_TwitterPopupName").popup("option", "positionTo", "window");

        /* InstagramPopupName */
        $("#L4DeveloperPage_InstagramPopupName").popup("option", "positionTo", "window");

    };

    // screen elements handler


    function L4DeveloperPage_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#L4DeveloperPage_L4DeveloperContainerName [name="FacebookIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("FacebookPopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#L4DeveloperPage_L4DeveloperContainerName [name="FacebookIconName"]');

        $(document).off("click", '#L4DeveloperPage_L4DeveloperContainerName [name="TwitterIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("TwitterPopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#L4DeveloperPage_L4DeveloperContainerName [name="TwitterIconName"]');

        $(document).off("click", '#L4DeveloperPage_L4DeveloperContainerName [name="InstagramIconName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("InstagramPopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#L4DeveloperPage_L4DeveloperContainerName [name="InstagramIconName"]');

    };

    $(document).off("pagebeforeshow", "#L4DeveloperPage").on("pagebeforeshow", "#L4DeveloperPage", function(event, ui) {
        Apperyio.CurrentScreen = "L4DeveloperPage";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    L4DeveloperPage_onLoad();
};

$(document).off("pagecreate", "#L4DeveloperPage").on("pagecreate", "#L4DeveloperPage", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    L4DeveloperPage_js();
});