/*
 * JS for ZGroomsListPageSonar generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'ac2f1913-e4fd-4043-aae9-c940ec4861d1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "L1SubmitAdvertisingPage",
    "location": "L1SubmitAdvertisingPage.html"
}, {
    "name": "XAdDialog07",
    "location": "XAdDialog07.html"
}, {
    "name": "XAdDialog05",
    "location": "XAdDialog05.html"
}, {
    "name": "XAdDialog08",
    "location": "XAdDialog08.html"
}, {
    "name": "XAdDialog03",
    "location": "XAdDialog03.html"
}, {
    "name": "XAdDialog02",
    "location": "XAdDialog02.html"
}, {
    "name": "L3TermsandConditionsPage",
    "location": "L3TermsandConditionsPage.html"
}, {
    "name": "XAdDialog04",
    "location": "XAdDialog04.html"
}, {
    "name": "YBridesSonar20170101002",
    "location": "YBridesSonar20170101002.html"
}, {
    "name": "YBridesSonar20170101003",
    "location": "YBridesSonar20170101003.html"
}, {
    "name": "D2EditProfilePage",
    "location": "D2EditProfilePage.html"
}, {
    "name": "L4DeveloperPage",
    "location": "L4DeveloperPage.html"
}, {
    "name": "J1SubmitTestimonialsPage",
    "location": "J1SubmitTestimonialsPage.html"
}, {
    "name": "B0AboutUsPage",
    "location": "B0AboutUsPage.html"
}, {
    "name": "A0HomePageOrg",
    "location": "A0HomePageOrg.html"
}, {
    "name": "D3DeleteProfilePage",
    "location": "D3DeleteProfilePage.html"
}, {
    "name": "H1SubmitNewsPage",
    "location": "H1SubmitNewsPage.html"
}, {
    "name": "L0ContactUsPage",
    "location": "L0ContactUsPage.html"
}, {
    "name": "MaterialDesignPage",
    "location": "MaterialDesignPage.html"
}, {
    "name": "YBridesSonar20170101001",
    "location": "YBridesSonar20170101001.html"
}, {
    "name": "K0HelpPage",
    "location": "K0HelpPage.html"
}, {
    "name": "XAdProfile003",
    "location": "XAdProfile003.html"
}, {
    "name": "ExamplePage",
    "location": "ExamplePage.html"
}, {
    "name": "XAdProfile001",
    "location": "XAdProfile001.html"
}, {
    "name": "A0Homepage",
    "location": "A0Homepage.html"
}, {
    "name": "XAdProfile002",
    "location": "XAdProfile002.html"
}, {
    "name": "ZGroomsSonar20170101003",
    "location": "ZGroomsSonar20170101003.html"
}, {
    "name": "J0TestimonialsPage",
    "location": "J0TestimonialsPage.html"
}, {
    "name": "XAdDialog09",
    "location": "XAdDialog09.html"
}, {
    "name": "ZGroomsSonar20170101001",
    "location": "ZGroomsSonar20170101001.html"
}, {
    "name": "ZGroomsSonar20170101002",
    "location": "ZGroomsSonar20170101002.html"
}, {
    "name": "ZGroomsListPageSonar",
    "location": "ZGroomsListPageSonar.html"
}, {
    "name": "H0NewsPage",
    "location": "H0NewsPage.html"
}, {
    "name": "YBridesListPageSonar",
    "location": "YBridesListPageSonar.html"
}, {
    "name": "G1SubmitEventsPage",
    "location": "G1SubmitEventsPage.html"
}, {
    "name": "L2SubmitSuggestionPage",
    "location": "L2SubmitSuggestionPage.html"
}, {
    "name": "E0DirectoryPage",
    "location": "E0DirectoryPage.html"
}, {
    "name": "G0EventsPage",
    "location": "G0EventsPage.html"
}, {
    "name": "F0ContactsPage",
    "location": "F0ContactsPage.html"
}, {
    "name": "C0SearchSoulmatePage",
    "location": "C0SearchSoulmatePage.html"
}, {
    "name": "D1CreateProfilePage",
    "location": "D1CreateProfilePage.html"
}, {
    "name": "D0RegisterSoulmatePage",
    "location": "D0RegisterSoulmatePage.html"
}, {
    "name": "XAdDialog11",
    "location": "XAdDialog11.html"
}, {
    "name": "XAdDialog10",
    "location": "XAdDialog10.html"
}, {
    "name": "XAdDialog06",
    "location": "XAdDialog06.html"
}, {
    "name": "XAdDialog01",
    "location": "XAdDialog01.html"
}, {
    "name": "I0SocialMediaPage",
    "location": "I0SocialMediaPage.html"
}];

function ZGroomsListPageSonar_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'SearchButtonName': 'ZGroomsListPageSonar_SearchButtonName',
        'YGroomsListPageSonarName': 'ZGroomsListPageSonar_YGroomsListPageSonarName',
        'ZGroomsSonar20170101001Name': 'ZGroomsListPageSonar_ZGroomsSonar20170101001Name',
        'ZGroomsSonar20170101001ButtonName': 'ZGroomsListPageSonar_ZGroomsSonar20170101001ButtonName',
        'ZGroomsSonar20170101002Name': 'ZGroomsListPageSonar_ZGroomsSonar20170101002Name',
        'ZGroomsSonar20170101002ButtonName': 'ZGroomsListPageSonar_ZGroomsSonar20170101002ButtonName',
        'ZGroomsSonar20170101003Name': 'ZGroomsListPageSonar_ZGroomsSonar20170101003Name',
        'ZGroomsSonar20170101003ButtonName': 'ZGroomsListPageSonar_ZGroomsSonar20170101003ButtonName',
        'SearchCollapsibleSetName': 'ZGroomsListPageSonar_SearchCollapsibleSetName',
        'NameWiseCollapsBlockName': 'ZGroomsListPageSonar_NameWiseCollapsBlockName',
        'NameWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_NameWiseCollapsBlockHeaderName',
        'NameWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_NameWiseCollapsBlockContainerName',
        'IdWiseCollapsBlockName': 'ZGroomsListPageSonar_IdWiseCollapsBlockName',
        'IdWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_IdWiseCollapsBlockHeaderName',
        'IdWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_IdWiseCollapsBlockContainerName',
        'AgeWiseCollapsBlockName': 'ZGroomsListPageSonar_AgeWiseCollapsBlockName',
        'AgeWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_AgeWiseCollapsBlockHeaderName',
        'AgeWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_AgeWiseCollapsBlockContainerName',
        'HeightWiseCollapsBlockName': 'ZGroomsListPageSonar_HeightWiseCollapsBlockName',
        'HeightWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_HeightWiseCollapsBlockHeaderName',
        'HeightWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_HeightWiseCollapsBlockContainerName',
        'CasteWiseCollapsBlockName': 'ZGroomsListPageSonar_CasteWiseCollapsBlockName',
        'CasteWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_CasteWiseCollapsBlockHeaderName',
        'CasteWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_CasteWiseCollapsBlockContainerName',
        'ClanWiseCollapsBlockName': 'ZGroomsListPageSonar_ClanWiseCollapsBlockName',
        'ClanWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_ClanWiseCollapsBlockHeaderName',
        'ClanWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_ClanWiseCollapsBlockContainerName',
        'LocationWiseCollapsBlockName': 'ZGroomsListPageSonar_LocationWiseCollapsBlockName',
        'LocationWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_LocationWiseCollapsBlockHeaderName',
        'LocationWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_LocationWiseCollapsBlockContainerName',
        'EducationWiseCollapsBlockName': 'ZGroomsListPageSonar_EducationWiseCollapsBlockName',
        'EducationWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_EducationWiseCollapsBlockHeaderName',
        'EducationWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_EducationWiseCollapsBlockContainerName',
        'ProfessionWiseCollapsBlockName': 'ZGroomsListPageSonar_ProfessionWiseCollapsBlockName',
        'ProfessionWiseCollapsBlockHeaderName': 'ZGroomsListPageSonar_ProfessionWiseCollapsBlockHeaderName',
        'ProfessionWiseCollapsBlockContainerName': 'ZGroomsListPageSonar_ProfessionWiseCollapsBlockContainerName'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'ZGroomsListPageSonar';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ZGroomsListPageSonar_onLoad = function() {
            ZGroomsListPageSonar_elementsExtraJS();

            ZGroomsListPageSonar_deviceEvents();
            ZGroomsListPageSonar_windowEvents();
            ZGroomsListPageSonar_elementsEvents();
        };

    // screen window events


    function ZGroomsListPageSonar_windowEvents() {

        $('#ZGroomsListPageSonar').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ZGroomsListPageSonar_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ZGroomsListPageSonar_elementsExtraJS() {
        // screen (ZGroomsListPageSonar) extra code

        /* YGroomsListPageSonarName */

        listView = $("#ZGroomsListPageSonar_YGroomsListPageSonarName");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ZGroomsListPageSonar_YGroomsListPageSonarName .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* ZGroomsSonar20170101001Name */

        /* ZGroomsSonar20170101002Name */

        /* ZGroomsSonar20170101003Name */

        /* SearchPopupName */
        $("#ZGroomsListPageSonar_SearchPopupName").popup("option", "positionTo", "window");

        /* NameWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_NameWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* IdWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_IdWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* AgeWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_AgeWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* HeightWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_HeightWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* CasteWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_CasteWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* ClanWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_ClanWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* LocationWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_LocationWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* EducationWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_EducationWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

        /* ProfessionWiseCollapsBlockName */

        $("#ZGroomsListPageSonar_ProfessionWiseCollapsBlockName .ui-collapsible-heading-toggle").attr("tabindex", "15");

    };

    // screen elements handler


    function ZGroomsListPageSonar_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ZGroomsListPageSonar_ZGroomsListPageSonarHeaderName [name="SearchButtonName"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    var popupElement = Apperyio("SearchPopupName");
                    if (popupElement.popup("option", "positionTo") === "origin") {
                        popupElement.popup("open", {
                            transition: "pop",
                            positionTo: "#" + $(this).attr("id")
                        });
                    } else {
                        popupElement.popup("open", {
                            transition: "pop"
                        });
                    };

                }
            },
        }, '#ZGroomsListPageSonar_ZGroomsListPageSonarHeaderName [name="SearchButtonName"]');

        $(document).off("click", '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101001Name"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ZGroomsSonar20170101001', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101001Name"]');

        $(document).off("click", '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101002Name"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ZGroomsSonar20170101002', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101002Name"]');

        $(document).off("click", '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101003Name"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ZGroomsSonar20170101003', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        }, '#ZGroomsListPageSonar_ZGroomsListPageSonarContainerName [name="ZGroomsSonar20170101003Name"]');

    };

    $(document).off("pagebeforeshow", "#ZGroomsListPageSonar").on("pagebeforeshow", "#ZGroomsListPageSonar", function(event, ui) {
        Apperyio.CurrentScreen = "ZGroomsListPageSonar";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ZGroomsListPageSonar_onLoad();
};

$(document).off("pagecreate", "#ZGroomsListPageSonar").on("pagecreate", "#ZGroomsListPageSonar", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ZGroomsListPageSonar_js();
});